apiVersion: v1
kind: ConfigMap
metadata:
  name: send-goal-move-base
  namespace: default
data:
  config-send-goal-move-base: |-
    {
        "broker_uri": "amqp://10.10.3.188:30000",
        "area_id":               0,
        "microphone_id":         0
    }
---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "send-goal-move-base"
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: send-goal-move-base
    spec:
      containers:
      - name: service 
        image: matheusdutra0207/move-base-goal:v1
        command: ["./bootstrap.sh"]       
        env:
        - name: ROS_MASTER_URI
          value: http://10.10.3.188:30015
        - name: ROS_IP
          value: 10.10.3.188
        imagePullPolicy: Always
        volumeMounts:
          - name: send-goal-move-base-config-volume
            mountPath: /opt/ros/src/move_base_send_goal/etc/config                   
      volumes:
      - name: send-goal-move-base-config-volume
        configMap:
          name: send-goal-move-base
          items:
          - key: config-send-goal-move-base
            path: config.json
      hostNetwork: true
